name: Deploy FastAPI to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx
    
    - name: Test with pytest
      run: |
        pytest test_main.py -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Create app directory if it doesn't exist
          mkdir -p /home/${{ secrets.SERVER_USERNAME }}/fastapi-app
          cd /home/${{ secrets.SERVER_USERNAME }}/fastapi-app
          
          # Pull latest code
          if [ -d ".git" ]; then
            git pull origin main
          else
            git clone https://github.com/${{ github.repository }} .
          fi
          
          # Ensure required packages are available
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv python3-full
          
          # Create virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          
          # Activate virtual environment and install dependencies
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          sudo tee /etc/systemd/system/fastapi-app.service > /dev/null <<EOF
          [Unit]
          Description=FastAPI application
          After=network.target
          
          [Service]
          Type=exec
          User=${{ secrets.SERVER_USERNAME }}
          WorkingDirectory=/home/${{ secrets.SERVER_USERNAME }}/fastapi-app
          Environment=PATH=/home/${{ secrets.SERVER_USERNAME }}/fastapi-app/venv/bin
          ExecStart=/home/${{ secrets.SERVER_USERNAME }}/fastapi-app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
          Restart=always
          RestartSec=3
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          sudo systemctl daemon-reload
          sudo systemctl enable fastapi-app
          sudo systemctl restart fastapi-app
          
          sleep 5
          if sudo systemctl is-active --quiet fastapi-app; then
            echo "FastAPI application started successfully"
            sleep 2
            curl -f http://localhost:8000/hello || echo "Warning: Health check failed"
          else
            echo "Failed to start FastAPI application"
            sudo systemctl status fastapi-app
            exit 1
          fi
